baseURL = "https://creative-biscuit-6b0cad.netlify.app/"
languageCode = "en-us"
title = "Shivang Patel"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Calin Tataru"
    description = "AI, Robotics and Spirituality"
    profilepic = "profile_pic.jpg"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "python"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:me@shivangapatel.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/shivaang12/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/shivang_engg/"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/shivaang14/"
    name = "fab fa-linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/"
    name = "fab fa-stack-overflow"
    weight = 5
